http {
    server {
        listen       80;
        server_name  example.com www.example.com;

        location / {
            root   /var/www/example ;
            index  index.html index.htm;
        }

        error_page 404 /404.html ;
        location = /404.html {
            root /var/www/example ;
        }
    }

    server {
        listen       80 ;
        server_name  anotherdomain.com www.anotherdomain.com ;

        location / {
            root   /var/www/another ;
            index  index.html ;
        }

        error_page 404 /404.html ;
        location = /404.html {
            root /var/www/another ;
        }
    }
    serverasdasd {
        listen       443 ssl ;
        server_name  secure.example.com www.secure.example.com ;

        ssl_certificate      /etc/ssl/certs/secure_example_com.crt ;
        ssl_certificate_key  /etc/ssl/private/secure_example_com.key ;

        error_page 404 /404.html ;
    }
}
