
set PROJECT_ROOT 					./;

# === Server 1 ===

server {
	listen							127.0.0.1:8080;
	listen 							localhost:8081;
	listen							8082;
	
	server_name 					www.example1.com  www.example2.com;

	root 							$PROJECT_ROOT/www/web1;
	
	index							index.htm index.html index.php;
	
	allow_methods					GET POST DELETE OPTIONS HEAD;
	
	client_max_body_size 			10M;

	autoindex						on;

	# Error Pages
	error_page						400 /errors/400.html;
	error_page						404 /errors/404.html;
	error_page						500 501 502 503 504 505 /errors/50x.html;

	# General/Default Location
	location / {
		allow_methods 				GET POST OPTIONS HEAD;
	}

	# Handler: Static pages
	location /pages {
		allow_methods				GET HEAD OPTIONS;
		alias						$PROJECT_ROOT/www/web1/pages/;
		client_max_body_size 		5M;
		index						index_pages.html;
	}
	
	location /pages/images {
		allow_methods				GET HEAD OPTIONS;
		alias 						$PROJECT_ROOT/www/web1/pages/images/;
		client_max_body_size 		5M;
		autoindex					off;
	}

	# Handler: CGI Executer
	location /cgi/php {
		allow_methods				GET POST OPTIONS HEAD;
		alias               		$PROJECT_ROOT/www/web1/cgi-bin/php/;
		index						index.php custom.php;
		cgi_pass					/usr/bin/php-cgi;
		client_max_body_size		5M;
	}
	
	location /cgi/py {
		allow_methods				GET POST OPTIONS HEAD;
		alias						$PROJECT_ROOT/www/web1/cgi-bin/py/;
		index						index.py custom.py;
		cgi_pass					/usr/bin/python3;
		client_max_body_size		5M;
	}
	
	# Handler: Uploads
	location /upload {
		allow_methods 				GET POST PUT PATCH DELETE OPTIONS HEAD;
		upload_enable				on;
		upload_store				$PROJECT_ROOT/www/web1/uploads;
		client_max_body_size		10M;
	}
	
	# Directory Listing Location
	location /auto {
		allow_methods				GET HEAD OPTIONS;
		root						$PROJECT_ROOT/www/web1/auto;
        autoindex                   on;
	}

	# Redirect Location
	location /redirect {
		allow_methods				GET HEAD OPTIONS;
		return 						301 /new-location;
	}

	# Error fallback page for any 50x server error:
	location /errors/50x.html {
		allow_methods				GET HEAD OPTIONS;
	}
}

# === Server 2 ===

server {
    listen							localhost:9090;
    server_name						www.example1.com;										
	server_name						www.example2.com;
	index							index2.html;
    root							$PROJECT_ROOT/www/web1;
}

# === Server 3 ===

server {
    listen							localhost:8080;
	server_name						www.example3.com;
	index							index2.html;
    root							$PROJECT_ROOT/www/web2;
}

# === Server 4 ===

server {
    listen							127.0.0.2:8085;
    root 							$PROJECT_ROOT/www/web2;
	index							index.html;

    client_max_body_size            10M;

	location /pages {
		allow_methods				GET HEAD OPTIONS;
		alias						$PROJECT_ROOT/www/web2/pages/;
		client_max_body_size 		5M;
		index						index_pages.html;
	}

    location /upload {
		allow_methods 				POST;
		upload_enable				on;
		upload_store				$PROJECT_ROOT/www/web2/uploads;
    	client_max_body_size		20;
	}
}

# === Server 5 ===

server {
    listen							127.0.0.2:8083;
    server_name						example.com;
    root							$PROJECT_ROOT/www/web1/html;
}

# === Server 6 ===

server {
    listen							127.0.0.1:8083;
    server_name						test.com;
    root							$PROJECT_ROOT/www/web2/html;
}
