server {
    listen 8080;
    server_name localhost;
    root www;
    index index.html;
    auto_index off;

    location / {
        root www-default;
        index home.html;
    }

    location /api/ {
        root www-api;
        index api.html;
        cgi_pass /usr/bin/python3;
        auto_index off;
    }

    location /static/ {
        root www-static;
        auto_index on;
    }

    location /upload/ {
        root www-upload;
        upload_enable on;
        upload_store www-upload/files;
    }
}
