server {
    listen 8080;
    server_name localhost test1.local;
    root www;
    index index.html;
    error_page 404 /404.html;
}

server {
    listen 8081;
    server_name example.com www.example.com;
    root www;
    index cgi.html;
    error_page 404 /404.html;
}

server {
    listen 8082;
    server_name api.local;
    root www-2;
    index index.html;
    auto_index on;
    cgi_pass /usr/bin/php-cgi;
}
